version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dmlog
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10

  flyway:
    image: flyway/flyway:10
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./db/migration:/flyway/sql
    command: >
      -url=jdbc:postgresql://postgres:5432/dmlog
      -user=postgres
      -password=postgres
      migrate