#server
server.port=8080
server.tomcat.threads.max=10

spring.application.name=dmlog

# virtual threads
spring.threads.virtual.enabled=true

# datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/dmlog
spring.datasource.username=postgres
spring.datasource.password=postgres

# hikari pool
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=10

# postgres performance
spring.datasource.hikari.data-source-properties.cachePrepStmts=true
spring.datasource.hikari.data-source-properties.prepStmtCacheSize=250
spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=2048
spring.datasource.hikari.data-source-properties.useServerPrepStmts=true

# logs úteis para jdbc
logging.level.org.springframework.jdbc.core=INFO