#server
server.port=${SERVER_PORT:8080}
server.tomcat.threads.max=10

spring.application.name=dmlog

# virtual threads
spring.threads.virtual.enabled=true

# datasource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password={DB_PASSWORD}

# hikari pool
spring.datasource.hikari.maximum-pool-size=${MAX_POOL_SIZE}
spring.datasource.hikari.minimum-idle=${MINIMUM_IDLE}

# postgres performance
spring.datasource.hikari.data-source-properties.cachePrepStmts=true
spring.datasource.hikari.data-source-properties.prepStmtCacheSize=250
spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=2048
spring.datasource.hikari.data-source-properties.useServerPrepStmts=true

# logs úteis para jdbc
logging.level.org.springframework.jdbc.core=INFO